import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import test from "node:test";

import {
  CATALOG_COUNTS,
  CATALOG_FAMILIES,
  CATALOG_VERSION,
} from "../src/catalog/index.js";
import { AUTHORED_FAMILY_ATLAS_CONTENT } from "../src/catalog/snapshot.js";
import {
  CANONICAL_INPUT_MEDIA,
  MAP_FAMILIES,
  MAP_FAMILY_GROUPS,
} from "../src/map-families/registry.js";
import FAMILY_BROWSER_CATALOG, {
  FAMILY_BROWSER_CATALOG as NAMED_FAMILY_BROWSER_CATALOG,
} from "../viewer/family-catalog.js";
import {
  buildFamilyBrowserCatalog,
  renderFamilyBrowserCatalogModule,
} from "../scripts/build-family-browser-catalog.mjs";

const GENERATED_MODULE_URL = new URL("../viewer/family-catalog.js", import.meta.url);
const GENERATOR_URL = new URL("../scripts/build-family-browser-catalog.mjs", import.meta.url);

function assertDeepFrozen(value, path = "catalog") {
  if (!value || typeof value !== "object") return;
  assert.equal(Object.isFrozen(value), true, `${path} must be frozen`);
  for (const [key, child] of Object.entries(value)) assertDeepFrozen(child, `${path}.${key}`);
}

function assertPlainText(value, path = "catalog") {
  if (typeof value === "string") {
    assert.doesNotMatch(value, /<\/?[a-z][^>]*>/iu, `${path} contains inline HTML`);
    assert.doesNotMatch(value, /&(amp|lt|gt|quot|apos|#39);/iu, `${path} contains an HTML entity`);
    return;
  }
  if (!value || typeof value !== "object") return;
  for (const [key, child] of Object.entries(value)) assertPlainText(child, `${path}.${key}`);
}

test("generated family browser catalog is current, browser-safe, and deeply frozen", async () => {
  assert.equal(FAMILY_BROWSER_CATALOG, NAMED_FAMILY_BROWSER_CATALOG);
  assertDeepFrozen(FAMILY_BROWSER_CATALOG);
  assertPlainText(FAMILY_BROWSER_CATALOG);

  const generatedSource = await readFile(GENERATED_MODULE_URL, "utf8");
  assert.match(generatedSource, /^\/\/ Generated by scripts\/build-family-browser-catalog\.mjs\. Do not edit\.\n/u);
  assert.doesNotMatch(generatedSource, /(?:from\s+|import\()["']node:/u);
  assert.equal(
    generatedSource,
    renderFamilyBrowserCatalogModule(buildFamilyBrowserCatalog()),
    "generated module must use stable deterministic formatting",
  );

  const check = spawnSync(process.execPath, [fileURLToPath(GENERATOR_URL), "--check"], {
    cwd: fileURLToPath(new URL("..", import.meta.url)),
    encoding: "utf8",
  });
  assert.equal(check.status, 0, check.stderr || check.stdout);
});

test("browser catalog preserves the governed release counts and registry dimensions", () => {
  assert.deepEqual(Object.keys(FAMILY_BROWSER_CATALOG), [
    "schemaVersion",
    "catalogVersion",
    "counts",
    "groups",
    "media",
    "families",
  ]);
  assert.equal(FAMILY_BROWSER_CATALOG.schemaVersion, 1);
  assert.equal(FAMILY_BROWSER_CATALOG.catalogVersion, CATALOG_VERSION);
  assert.deepEqual(FAMILY_BROWSER_CATALOG.counts, CATALOG_COUNTS);
  assert.deepEqual(FAMILY_BROWSER_CATALOG.groups, MAP_FAMILY_GROUPS);
  assert.deepEqual(FAMILY_BROWSER_CATALOG.media, CANONICAL_INPUT_MEDIA);
  assert.deepEqual(
    FAMILY_BROWSER_CATALOG.families.map((family) => family.id),
    CATALOG_FAMILIES.map((family) => family.id),
  );

  const members = FAMILY_BROWSER_CATALOG.families.flatMap((family) => family.members);
  assert.equal(members.length, 144);
  assert.equal(members.filter((member) => member.status !== "rejected").length, CATALOG_COUNTS.approved);
  for (const status of ["documented", "executable", "unavailable", "rejected"]) {
    assert.equal(
      members.filter((member) => member.status === status).length,
      CATALOG_COUNTS[status],
      status,
    );
  }
});

test("each family joins authored release truth to the complete browser-safe production contract", () => {
  const catalogById = new Map(CATALOG_FAMILIES.map((family) => [family.id, family]));
  const manifestById = new Map(MAP_FAMILIES.map((family) => [family.id, family]));

  for (const family of FAMILY_BROWSER_CATALOG.families) {
    const catalogFamily = catalogById.get(family.id);
    const manifest = manifestById.get(family.id);
    assert.ok(catalogFamily, family.id);
    assert.ok(manifest, family.id);
    assert.deepEqual(Object.keys(family), [
      "id",
      "version",
      "title",
      "group",
      "question",
      "oneLine",
      "summary",
      "executableMemberIds",
      "maturity",
      "renderer",
      "questions",
      "roles",
      "grammar",
      "transformations",
      "validation",
      "evidence",
      "variants",
      "multiples",
      "controls",
      "selections",
      "followUps",
      "mediaAdapters",
      "abstention",
      "members",
    ]);
    assert.equal(family.title, catalogFamily.title);
    assert.equal(family.group, catalogFamily.group);
    assert.equal(family.question, catalogFamily.question);
    assert.equal(family.oneLine, catalogFamily.oneLine);
    assert.equal(family.summary, catalogFamily.summary);
    assert.deepEqual(family.executableMemberIds, catalogFamily.executableMemberIds);
    assert.equal(family.version, manifest.version);
    assert.equal(family.maturity, manifest.maturity);
    assert.deepEqual(family.renderer, manifest.renderer);
    assert.deepEqual(family.questions, manifest.questions);
    assert.deepEqual(family.roles, {
      required: catalogFamily.requiredRoles,
      optional: catalogFamily.optionalRoles,
      minimumRecords: manifest.data.minimumRecords,
      maximumRecords: manifest.data.maximumRecords,
    });
    assert.deepEqual(family.grammar, manifest.grammar);
    assert.deepEqual(family.transformations, {
      deterministic: manifest.transformation,
      enrichment: manifest.enrichment,
    });
    assert.deepEqual(family.validation, manifest.validation);
    assert.deepEqual(family.evidence, manifest.evidence);
    assert.deepEqual(family.variants, manifest.variants);
    assert.deepEqual(family.multiples, manifest.multiples);
    assert.deepEqual(family.controls, manifest.controls);
    assert.deepEqual(family.selections, manifest.selections);
    assert.deepEqual(family.followUps, manifest.followUps);
    assert.deepEqual(family.mediaAdapters, manifest.mediaAdapters);
    assert.deepEqual(family.abstention, catalogFamily.abstention);
  }
});

test("members keep authored band separate from release status and retain governed reasons", () => {
  const authoredByFamily = new Map(AUTHORED_FAMILY_ATLAS_CONTENT.map((family) => [family.id, family]));
  const catalogByFamily = new Map(CATALOG_FAMILIES.map((family) => [family.id, family]));

  for (const family of FAMILY_BROWSER_CATALOG.families) {
    const authoredMembers = new Map(authoredByFamily.get(family.id).members.map((member) => [member.id, member]));
    const catalogMembers = new Map(catalogByFamily.get(family.id).members.map((member) => [member.id, member]));

    for (const member of family.members) {
      const authored = authoredMembers.get(member.id);
      const catalog = catalogMembers.get(member.id);
      assert.ok(authored, `${family.id}/${member.id}`);
      assert.ok(catalog, `${family.id}/${member.id}`);
      assert.deepEqual(Object.keys(member), [
        "id",
        "name",
        "authoredStatus",
        "authoredQuantityBand",
        "executableQuantityBand",
        "status",
        "when",
        "rationale",
        "band",
        "lineage",
        "rejectionReason",
        "unavailableReason",
        "requirements",
        "roles",
        "guidance",
        "sourcePolicy",
        "projector",
        "payload",
        "selectionPolicy",
        "representationCapabilities",
        "renderer",
        "mediaPolicy",
        "fixtureId",
      ]);
      assert.equal(member.authoredStatus, authored.status);
      assert.deepEqual(member.authoredQuantityBand, catalog.authoredBand ?? authored.band);
      assert.deepEqual(member.executableQuantityBand, catalog.executableBand ?? []);
      assert.equal(member.status, catalog.status);
      assert.equal(member.when, catalog.when);
      assert.equal(member.band, catalog.band);
      assert.deepEqual(member.requirements, catalog.requirements ?? []);
      assert.deepEqual(
        member.representationCapabilities,
        catalog.representationCapabilities ?? null,
      );
      assert.equal(member.rejectionReason, catalog.rejectionReason ?? null);
      assert.equal(member.unavailableReason, catalog.unavailableReason ?? null);
      assert.deepEqual(member.renderer, catalog.rendererId
        ? {
            id: catalog.rendererId,
            version: catalog.rendererVersion,
            variantId: catalog.rendererVariantId,
          }
        : null);
      assert.deepEqual(member.roles, catalog.roleSchema ?? null);
      assert.deepEqual(member.guidance, catalog.guidance ?? null);
      assert.deepEqual(member.sourcePolicy, catalog.sourcePolicy ?? null);
      assert.deepEqual(member.projector, catalog.projector ?? null);
      assert.deepEqual(member.payload, catalog.payload ?? null);
      assert.deepEqual(member.selectionPolicy, catalog.selectionPolicy ?? null);
      assert.deepEqual(member.mediaPolicy, catalog.mediaPolicy ?? null);
      assert.equal(member.fixtureId, catalog.fixtureId ?? null);
    }
  }

  const annotated = FAMILY_BROWSER_CATALOG.families.find((family) => family.id === "annotated-specimen");
  const callout = annotated.members.find((member) => member.id === "callout-overlay");
  const layered = annotated.members.find((member) => member.id === "layered-lens");
  assert.equal(callout.authoredStatus, "core");
  assert.equal(callout.status, "unavailable");
  assert.match(callout.unavailableReason, /visible specimen/u);
  assert.deepEqual(callout.representationCapabilities, {
    version: 1,
    constraints: {
      dimensionality: ["2d"],
      form: ["callout-overlay"],
      interaction: [],
      motion: ["static"],
      projection: ["none"],
    },
  });
  assert.equal(
    layered.lineage,
    "Tufte, layering and separation, Envisioning Information, pp. 53–65",
  );

  const distribution = FAMILY_BROWSER_CATALOG.families.find((family) => family.id === "distribution");
  const uncertain = distribution.members.find((member) => member.id === "quantile-dots");
  assert.match(uncertain.lineage, /Fernandes, Walls, Munson, Hullman & Kay/u);
});
