import assert from "node:assert/strict";
import { access, mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import {
  MANAGED_MARKER,
  projectPaths,
  readJson,
  setupProject,
  writeJsonAtomic,
} from "../src/project.js";

async function fixture(t) {
  const root = await mkdtemp(join(tmpdir(), "attend-project-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  return root;
}

async function exists(path) {
  try {
    await access(path);
    return true;
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    throw error;
  }
}

test("dry-run returns the complete setup plan and writes nothing", async (t) => {
  const root = await fixture(t);
  const paths = projectPaths(root);

  const result = await setupProject({ root, dryRun: true });

  assert.equal(result.root, root);
  assert.equal(result.dryRun, true);
  assert.deepEqual(result.planned, [
    { path: ".attend/project.json", action: "create", managed: true },
    { path: ".attend/.gitignore", action: "create", managed: true },
  ]);
  assert.deepEqual(result.created, []);
  assert.deepEqual(result.updated, []);
  assert.deepEqual(result.unchanged, []);
  assert.deepEqual(result.conflicts, []);
  assert.equal(await exists(paths.directory), false);
});

test("setup is project-scoped, inspectable, and idempotent", async (t) => {
  const root = await fixture(t);
  const paths = projectPaths(root);

  const first = await setupProject({ root });
  assert.deepEqual(first.created, [
    ".attend/project.json",
    ".attend/.gitignore",
  ]);
  assert.deepEqual(first.unchanged, []);

  const project = await readJson(paths.project);
  assert.equal(project.managedBy, MANAGED_MARKER);
  assert.equal(project.schemaVersion, 1);
  assert.deepEqual(project.sourceScope, {
    root: ".",
    recursiveExcludes: [".*", "node_modules"],
    explicitHiddenSourcesAllowed: true,
  });
  assert.deepEqual(project.view, { id: "phrase-list", version: 1 });
  assert.match(await readFile(paths.gitignore, "utf8"), /\/local\//);

  const second = await setupProject({ root });
  assert.deepEqual(second.created, []);
  assert.deepEqual(second.updated, []);
  assert.deepEqual(second.unchanged, [
    ".attend/project.json",
    ".attend/.gitignore",
  ]);
  assert.deepEqual(
    second.planned.map(({ path, action }) => ({ path, action })),
    [
      { path: ".attend/project.json", action: "unchanged" },
      { path: ".attend/.gitignore", action: "unchanged" },
    ],
  );
});

test("setup copies an explicitly supplied skill with a managed marker", async (t) => {
  const root = await fixture(t);
  const source = join(root, "skill-template.md");
  await writeFile(
    source,
    "---\nname: attend-visualize\ndescription: Open a local Attend visualization.\n---\n\n# Attend visualize\n\nUse the local viewer.\n",
  );

  const preview = await setupProject({ root, dryRun: true, skillSource: source });
  assert.deepEqual(
    preview.planned.map(({ path, action }) => ({ path, action })),
    [
      { path: ".attend/project.json", action: "create" },
      { path: ".attend/.gitignore", action: "create" },
      { path: ".agents/skills/attend-visualize/SKILL.md", action: "create" },
    ],
  );
  assert.equal(await exists(projectPaths(root).skill), false);

  const installed = await setupProject({ root, skillSource: source });
  assert.deepEqual(installed.created, [
    ".attend/project.json",
    ".attend/.gitignore",
    ".agents/skills/attend-visualize/SKILL.md",
  ]);
  const skill = await readFile(projectPaths(root).skill, "utf8");
  assert.ok(skill.startsWith("---\n"), "YAML frontmatter remains at byte zero");
  assert.match(
    skill,
    /^---\nname: attend-visualize\ndescription: Open a local Attend visualization\.\n---\n/,
  );
  assert.match(
    skill,
    /---\n<!-- attend-managed: generated by Attend setup -->\n\n# Attend visualize/,
  );
  assert.match(skill, new RegExp(MANAGED_MARKER));
  assert.match(skill, /# Attend visualize/);

  const repeated = await setupProject({ root, skillSource: source });
  assert.deepEqual(repeated.created, []);
  assert.deepEqual(repeated.updated, []);
  assert.deepEqual(repeated.unchanged, [
    ".attend/project.json",
    ".attend/.gitignore",
    ".agents/skills/attend-visualize/SKILL.md",
  ]);
});

test("unmanaged conflicts are previewed and stop setup before any write", async (t) => {
  const root = await fixture(t);
  const paths = projectPaths(root);
  await mkdir(paths.directory, { recursive: true });
  await writeFile(paths.project, '{"ownedBy":"the user"}\n');

  const preview = await setupProject({ root, dryRun: true });
  assert.deepEqual(preview.conflicts, [".attend/project.json"]);
  assert.equal(preview.planned[0].action, "conflict");
  assert.equal(preview.planned[1].action, "create");
  assert.equal(await exists(paths.gitignore), false);

  await assert.rejects(
    setupProject({ root }),
    (error) =>
      error.code === "UNMANAGED_FILE" &&
      error.path === ".attend/project.json" &&
      error.plan.conflicts[0] === ".attend/project.json",
  );
  assert.equal(await readFile(paths.project, "utf8"), '{"ownedBy":"the user"}\n');
  assert.equal(await exists(paths.gitignore), false);
});

test("differing managed files can be repaired without touching unmarked files", async (t) => {
  const root = await fixture(t);
  const paths = projectPaths(root);
  await mkdir(paths.directory, { recursive: true });
  await writeFile(paths.project, `{"managedBy":"${MANAGED_MARKER}","old":true}\n`);

  const result = await setupProject({ root });
  assert.deepEqual(result.updated, [".attend/project.json"]);
  assert.deepEqual(result.created, [".attend/.gitignore"]);
  assert.equal((await readJson(paths.project)).old, undefined);
});

test("generic JSON helpers round-trip through an atomic write", async (t) => {
  const root = await fixture(t);
  const path = join(root, "nested", "state.json");
  const value = { revision: 4, selectedIds: ["phrase_1"] };

  await writeJsonAtomic(path, value);

  assert.deepEqual(await readJson(path), value);
  assert.equal(await readFile(path, "utf8"), `${JSON.stringify(value, null, 2)}\n`);
});

test("setup refuses symlinked .attend and .agents write parents", async (t) => {
  const base = await fixture(t);

  const attendRoot = join(base, "attend-root");
  const attendOutside = join(base, "attend-outside");
  await mkdir(attendRoot);
  await mkdir(attendOutside);
  await symlink(attendOutside, join(attendRoot, ".attend"));
  await assert.rejects(
    setupProject({ root: attendRoot }),
    (error) => error.code === "UNSAFE_SYMLINK" && error.path === join(attendRoot, ".attend"),
  );
  assert.equal(await exists(join(attendOutside, "project.json")), false);

  const agentsRoot = join(base, "agents-root");
  const agentsOutside = join(base, "agents-outside");
  const skillSource = join(base, "skill.md");
  await mkdir(agentsRoot);
  await mkdir(agentsOutside);
  await writeFile(skillSource, "---\nname: test\n---\n\n# Test\n");
  await symlink(agentsOutside, join(agentsRoot, ".agents"));
  await assert.rejects(
    setupProject({ root: agentsRoot, skillSource }),
    (error) => error.code === "UNSAFE_SYMLINK" && error.path === join(agentsRoot, ".agents"),
  );
  assert.equal(await exists(join(agentsOutside, "skills", "attend-visualize", "SKILL.md")), false);
  assert.equal(await exists(join(agentsRoot, ".attend")), false, "planning fails before setup writes");
});
