window.ATTEND_SYSTEM = {
  meta: {
    version: "0.6.0",
    inspectedAt: "2026-08-27",
    sourceModules: 32,
    conceptualComponents: 21,
    responseRoutes: 3,
    activeObservers: 0,
  },
  phases: [
    { id: "entry", name: "Invocation boundary", note: "host-owned" },
    { id: "compile", name: "Govern + compile", note: "one-shot CLI" },
    { id: "runtime", name: "View state + service", note: "project-local" },
    { id: "answer", name: "Interrogation routes", note: "reactive" },
    { id: "proposed", name: "Proposed observer", note: "not current" },
  ],
  components: [
    { id: "active-agent", name: "Active coding agent", path: "../agent-skill/attend-visualize/SKILL.md" },
    { id: "managed-skill", name: "Managed Attend skill", path: "../agent-skill/attend-visualize/SKILL.md" },
    { id: "attend-cli", name: "Attend CLI", path: "../src/cli.js" },
    { id: "project-boundary", name: "Project boundary", path: "../src/project.js" },
    { id: "source-inspector", name: "Source inspector", path: "../src/inspect.js" },
    { id: "opportunity-ledger", name: "Opportunity ledger", path: "../src/opportunity-store.js" },
    { id: "experiment-ledger", name: "Experiment ledger", path: "../src/exploration-store.js" },
    { id: "map-compiler", name: "Map compiler", path: "../src/map/index.js" },
    { id: "family-catalog", name: "Family catalog", path: "../src/catalog/index.js" },
    { id: "evidence-store", name: "Evidence store", path: "../src/evidence.js" },
    { id: "data-package", name: "DataPackage", path: "../src/pipeline/compile.js" },
    { id: "visualization-session", name: "Visualization session", path: "../src/session-store.js" },
    { id: "service-supervisor", name: "Service supervisor", path: "../src/service.js" },
    { id: "attend-daemon", name: "Attend daemon", path: "../src/server.js" },
    { id: "browser-viewer", name: "Browser viewer", path: "../viewer/app.js" },
    { id: "chat-router", name: "Chat router", path: "../src/chat-route.js" },
    { id: "host-bridge", name: "Host bridge", path: "../src/host-bridge.js" },
    { id: "question-context", name: "Question context", path: "../src/question-context.js" },
    { id: "question-worker", name: "Question worker", path: "../src/question-worker.js" },
    { id: "local-model", name: "Local model process", path: "../src/local-model.js" },
    { id: "detached-provider", name: "Detached provider worker", path: "../src/agent-runner.js" },
  ],
  modules: [
    {
      id: "host", phase: "entry", code: "H", name: "Active coding agent",
      status: "external", x: 1.0, y: 1.0, w: 1.75, d: 1.55, h: 38,
      members: ["active-agent"],
      purpose: "Owns the coding task and decides when to invoke Attend. Today, the semantic opportunity judgment happens here, not inside a separate Attend observer.",
      build: "The host follows the installed managed skill and invokes bounded CLI commands. Host-attached sidebar questions only return when this agent explicitly polls the bridge.",
      limit: "Attend cannot wake, follow, or mutate a finished host conversation. A running Attend page does not make the coding agent continuously active.",
      facts: ["The trigger is policy in the host agent", "Host-attached chat is polling, not observation"],
      sources: [
        { path: "../agent-skill/attend-visualize/SKILL.md", note: "The active root agent owns opportunity judgment." },
        { path: "../src/host-bridge.js", note: "The bridge leases bounded questions to an attached host." },
      ],
    },
    {
      id: "skill", phase: "entry", code: "SK", name: "Managed Attend skill",
      status: "policy", x: 3.35, y: 1.0, w: 1.9, d: 1.6, h: 46,
      members: ["managed-skill"],
      purpose: "Defines Attend's primary proactive EDA lane, the narrower exact-match lane for requested visuals, authorized sources, and the governed command sequence the host should follow.",
      build: "A packaged SKILL.md is installed into the host. It is instructions interpreted by the current coding agent, not an executable background loop.",
      limit: "Policy is only as strong as its admission contract. A named visual form must be treated as mandatory or the host can choose a valid but wrong substitute.",
      facts: ["Policy layer, not a process", "Must fail closed on unsupported exact forms"],
      sources: [
        { path: "../agent-skill/attend-visualize/SKILL.md", note: "Opportunity, evidence, representation, and abstention policy." },
      ],
    },
    {
      id: "cli", phase: "compile", code: "CLI", name: "CLI control plane",
      status: "live", x: 5.75, y: 1.0, w: 2.0, d: 1.75, h: 58,
      members: ["attend-cli"],
      purpose: "The one-shot command boundary for inspection, exploration, compilation, session creation, service lifecycle, feedback, and workspace operations.",
      build: "Each invocation validates command input, resolves the project, calls a domain store or compiler, writes durable state, prints a receipt, and exits.",
      limit: "The CLI is not an agent loop. Its process lifetime ends after the requested command unless it explicitly starts the detached page service.",
      facts: ["One-shot orchestration", "Mutations enter through strict commands"],
      sources: [
        { path: "../src/cli.js", note: "Command dispatcher and lifecycle orchestration." },
        { path: "../src/mcp-server.js", note: "Optional bounded MCP command surface." },
      ],
    },
    {
      id: "scope", phase: "compile", code: "SC", name: "Scope + source inspection",
      status: "live", x: 8.2, y: .75, w: 2.15, d: 1.9, h: 42,
      members: ["project-boundary", "source-inspector"],
      purpose: "Fixes the trusted project root, rejects escapes, and reports content-free source shape before any evidence-backed request is compiled.",
      build: "Project resolution and path guards constrain every source. Inspection returns type, size, and shape receipts without returning source bodies.",
      limit: "A valid project path is not authorization to scan everything. The host must still name the smallest relevant source scope.",
      facts: ["Project root is the hard filesystem boundary", "Inspection is content-free"],
      sources: [
        { path: "../src/project.js", note: "Project discovery and below-root path enforcement." },
        { path: "../src/inspect.js", note: "Source-shape inspection." },
      ],
    },
    {
      id: "experiments", phase: "compile", code: "EX", name: "Opportunity + experiment ledgers",
      status: "live", x: 6.1, y: 4.0, w: 2.45, d: 1.95, h: 54, stack: 2,
      members: ["opportunity-ledger", "experiment-ledger"],
      purpose: "Records the pre-result decision, immutable experiment plan, staged artifact lineage, assessment, promotion, and feedback.",
      build: "Content-free checkpoint records and append-only experiment events are written under project-local state with deterministic identities and replay checks.",
      limit: "These records show what Attend attempted and how it was classified. They do not prove anyone saw it, used it, or achieved a different outcome.",
      facts: ["Pre-result intent is durable", "Activity is not impact"],
      sources: [
        { path: "../src/opportunity-store.js", note: "OpportunityCheck storage and privacy-safe host boundary IDs." },
        { path: "../src/exploration-store.js", note: "Exploration, experiment, and event ledger." },
      ],
    },
    {
      id: "compiler", phase: "compile", code: "MC", name: "Governed map compiler",
      status: "live", x: 8.8, y: 3.5, w: 2.35, d: 2.05, h: 72,
      members: ["map-compiler", "family-catalog"],
      purpose: "Validates a declarative map request against an executable family contract, reopens sources, verifies exact evidence, and resolves one bundled renderer.",
      build: "The compiler validates roles, data types, graph shape, source quotes, and the chosen catalog member before producing the canonical artifact.",
      limit: "It can prove the submitted member is executable. Without exact representation intent, it cannot prove that member matches the visual form the user originally named.",
      facts: ["No caller-supplied renderer code", "Exact evidence before artifact creation"],
      sources: [
        { path: "../src/map/index.js", note: "Strict map request compiler." },
        { path: "../src/catalog/index.js", note: "Executable Family Atlas catalog." },
        { path: "../src/map-families/registry.js", note: "Family/member contracts and renderer receipts." },
      ],
    },
    {
      id: "artifact", phase: "compile", code: "PK", name: "Package + private evidence",
      status: "authority", x: 10.15, y: 6.0, w: 2.55, d: 2.15, h: 86, stack: 3,
      members: ["evidence-store", "data-package"],
      purpose: "Binds an immutable public DataPackage to a private evidence store containing the exact source claims the browser is not allowed to receive.",
      build: "Stable hashes connect public marks to private evidence. The browser receives a closed render projection; source bodies and private locators stay behind the loopback service.",
      limit: "The package proves provenance and renderer identity, not that its analytical form was the right response to the user's request.",
      facts: ["Public artifact and private evidence are separated", "Hashes bind the two stores"],
      sources: [
        { path: "../src/pipeline/compile.js", note: "Canonical DataPackage compilation." },
        { path: "../src/evidence.js", note: "Private package-bound evidence store." },
      ],
    },
    {
      id: "session", phase: "runtime", code: "SS", name: "Visualization session",
      status: "state", x: 7.7, y: 7.05, w: 2.35, d: 2.0, h: 64, stack: 2,
      members: ["visualization-session"],
      purpose: "Persists the artifact identity, selected marks, question jobs, answers, route snapshots, and revisioned browser state.",
      build: "The session store applies revision guards and re-derives selections and implicated evidence on the server before committing changes.",
      limit: "This is application state, not a provider thread or autonomous agent context. Answer packets are rebuilt from it for each question.",
      facts: ["Durable UI/conversation state", "Not an LLM session"],
      sources: [
        { path: "../src/session-store.js", note: "Session creation, selection, question, and answer mutations." },
      ],
    },
    {
      id: "service", phase: "runtime", code: "SV", name: "Detached page service",
      status: "reactive", x: 5.0, y: 7.35, w: 2.15, d: 2.0, h: 70, stack: 2,
      members: ["service-supervisor", "attend-daemon"],
      purpose: "Runs the loopback library and session APIs, queues questions, serves private evidence through bounded endpoints, and owns response-worker lifecycle.",
      build: "The CLI starts one detached Node process scoped to the project. The supervisor reuses it and, for local chat, also owns the llama.cpp lifecycle.",
      limit: "It is active as a server but reactive as a product. It receives HTTP work; it does not observe coding turns or decide when to intervene.",
      facts: ["Long-running project process", "Page/question daemon, not observer"],
      sources: [
        { path: "../src/service.js", note: "Detached process and worker supervision." },
        { path: "../src/server.js", note: "Loopback HTTP routes and question queue." },
      ],
    },
    {
      id: "viewer", phase: "runtime", code: "UI", name: "Browser viewer",
      status: "surface", x: 2.25, y: 7.15, w: 2.2, d: 2.0, h: 46,
      members: ["browser-viewer"],
      purpose: "Renders the fixed catalog member, lets a person select marks, and attaches that exact visual state to sidebar questions.",
      build: "A closed browser projection drives bundled renderers. Selection and question mutations return to the loopback service under session revisions.",
      limit: "Opening or selecting a view is exposure/activity evidence at most. It is not proof that the result influenced a later action.",
      facts: ["Selection-aware surface", "No project filesystem access"],
      sources: [
        { path: "../viewer/app.js", note: "Viewer shell, selection, and question interactions." },
        { path: "../viewer/family-renderers.js", note: "Bundled fixed renderers." },
      ],
    },
    {
      id: "router", phase: "answer", code: "RT", name: "Question route snapshot",
      status: "live", x: 3.2, y: 10.0, w: 2.0, d: 1.7, h: 38,
      members: ["chat-router"],
      purpose: "Chooses and snapshots the response boundary when a question is queued: private local model, host-attached agent, or explicit detached provider.",
      build: "The resolved route is stored with the job so later configuration changes cannot redirect already-queued private evidence.",
      limit: "Route choice controls where evidence goes; it does not create a durable reasoning thread. Every response gets a reconstructed bounded context.",
      facts: ["Route frozen at enqueue", "Three explicit response boundaries"],
      sources: [
        { path: "../src/chat-route.js", note: "Route validation, resolution, and snapshots." },
      ],
    },
    {
      id: "responder", phase: "answer", code: "QA", name: "Bounded answer runner",
      status: "reactive", x: 6.0, y: 10.1, w: 2.65, d: 1.95, h: 58,
      members: ["question-context", "question-worker", "local-model", "detached-provider"],
      purpose: "Rebuilds a small packet from the current selection and implicated evidence, calls the selected response boundary, and commits a guarded answer.",
      build: "Local chat uses one owned llama.cpp process. Detached Codex or Claude routes start a fresh ephemeral process per question. Both receive reconstructed context.",
      limit: "The answer runner has no ambient project tools. Detached provider routes are explicit because they change the evidence boundary.",
      facts: ["Context rebuilt per question", "Local process can persist; provider worker does not"],
      sources: [
        { path: "../src/question-context.js", note: "Bounded context reconstruction from stored state." },
        { path: "../src/question-worker.js", note: "Question lease, inference, and answer commit." },
        { path: "../src/local-model.js", note: "Owned private llama.cpp process." },
        { path: "../src/agent-runner.js", note: "Fresh detached Codex/Claude process." },
      ],
    },
    {
      id: "hostbridge", phase: "answer", code: "HB", name: "Host-attached bridge",
      status: "polling", x: .8, y: 4.55, w: 1.85, d: 1.7, h: 34,
      members: ["host-bridge"],
      purpose: "Makes a queued Attend question available to the already-running host coding agent as a bounded packet.",
      build: "The host explicitly polls, leases a matching question, receives the verified packet, and later submits the response under the lease.",
      limit: "No listener means no response. This bridge is an attachment seam, not a separate agent that follows the host session continuously.",
      facts: ["Explicit host polling", "Cannot wake a dormant session"],
      sources: [
        { path: "../src/host-bridge.js", note: "Question polling, leasing, packet construction, and response commit." },
      ],
    },
    {
      id: "hostevents", phase: "proposed", code: "EV", name: "Authenticated host events",
      status: "proposed", x: 12.1, y: 1.4, w: 2.05, d: 1.65, h: 34,
      members: [],
      purpose: "Would deliver versioned coding-session lifecycle events with stable source identity, sequence, producer epoch, and bounded task shape.",
      build: "Use authenticated local IPC or a signed outbox. Delivery is at-least-once; deterministic operation IDs make processing idempotent and expose conflicts or gaps.",
      limit: "Conductor environment-variable names suggest a seam but do not define a supported protocol. Attend must not scrape transcripts or depend on an undocumented outbox.",
      facts: ["Proposed, not implemented", "At-least-once + idempotent, not magical exactly-once"],
      sources: [
        { path: "observer-design.md", note: "Reviewed host event and observer protocol." },
      ],
    },
    {
      id: "observer", phase: "proposed", code: "OB", name: "Isolated observer sessions",
      status: "proposed", x: 12.2, y: 4.3, w: 2.45, d: 2.0, h: 72, stack: 2,
      members: [],
      purpose: "Would maintain one narrow, session-scoped observer context per host session: detect eligible visual jobs, abstain, or propose under an interruption budget.",
      build: "One project daemon can schedule isolated ObserverSessions with bounded inboxes, fairness, explicit authority modes, and context rebuilt from typed events.",
      limit: "Start in shadow mode. Suggestion needs approval; automatic staging must wait for a scoped source-transform worker and must never mutate the global current pointer.",
      facts: ["One daemon, isolated logical sessions", "Shadow before suggestion; staging deferred"],
      sources: [
        { path: "observer-design.md", note: "Reviewed observer responsibilities and authority levels." },
      ],
    },
    {
      id: "impact", phase: "proposed", code: "IL", name: "Impact event ledger",
      status: "proposed", x: 12.2, y: 7.3, w: 2.45, d: 2.1, h: 82, stack: 4,
      members: [],
      purpose: "Would join interventions to explicit delivery, use, reversal, assignment, and outcome receipts without copying prompts, transcripts, or source bodies.",
      build: "Append-only strict event schemas use per-project HMAC join keys, authenticated producers, retention rules, stable operation IDs, and rebuildable projections.",
      limit: "The ledger must keep activity, exposure, influence, and impact separate. Causal impact requires an immutable pre-result assignment and a declared metric/window.",
      facts: ["Proposed, not implemented", "No causal claim without assignment + outcome"],
      sources: [
        { path: "observer-design.md", note: "Reviewed impact protocol and privacy boundary." },
      ],
    },
  ],
  edges: [
    { id: "e01", from: "host", to: "skill", route: "invoke", label: "applies visualization policy" },
    { id: "e02", from: "skill", to: "cli", route: "invoke", label: "invokes bounded commands" },
    { id: "e03", from: "cli", to: "scope", route: "build", label: "resolves root + inspects scope" },
    { id: "e04", from: "cli", to: "experiments", route: "experiment", label: "records checkpoints + plans" },
    { id: "e05", from: "cli", to: "compiler", route: "build", label: "submits declarative request" },
    { id: "e06", from: "scope", to: "compiler", route: "build", label: "authorizes bounded sources" },
    { id: "e07", from: "compiler", to: "artifact", route: "build", label: "writes verified package" },
    { id: "e08", from: "artifact", to: "session", route: "build", label: "binds public + private state" },
    { id: "e09", from: "experiments", to: "session", route: "experiment", label: "verifies staged provenance" },
    { id: "e10", from: "cli", to: "service", route: "build", label: "starts or reuses service" },
    { id: "e11", from: "service", to: "viewer", route: "build", label: "serves library + artifact" },
    { id: "e12", from: "viewer", to: "service", route: "question", label: "posts selection + question" },
    { id: "e13", from: "service", to: "router", route: "question", label: "queues with route snapshot" },
    { id: "e14", from: "router", to: "responder", route: "question", label: "runs owned response route" },
    { id: "e15", from: "responder", to: "artifact", route: "question", label: "reads implicated evidence" },
    { id: "e16", from: "responder", to: "session", route: "question", label: "commits guarded answer" },
    { id: "e17", from: "router", to: "hostbridge", route: "host", label: "offers host-attached route" },
    { id: "e18", from: "hostbridge", to: "host", route: "host", label: "returns bounded packet on poll" },
    { id: "p01", from: "host", to: "hostevents", route: "observe", label: "emits typed lifecycle boundary", proposed: true },
    { id: "p02", from: "hostevents", to: "observer", route: "observe", label: "delivers authenticated event", proposed: true },
    { id: "p03", from: "observer", to: "experiments", route: "observe", label: "records abstention or proposal", proposed: true },
    { id: "p04", from: "observer", to: "compiler", route: "observe", label: "stages only inside prior authority", proposed: true },
    { id: "p05", from: "observer", to: "impact", route: "impact", label: "records activity receipt", proposed: true },
    { id: "p06", from: "viewer", to: "impact", route: "impact", label: "records explicit render ack", proposed: true },
    { id: "p07", from: "hostevents", to: "impact", route: "impact", label: "records authorized use/outcome", proposed: true },
    { id: "p08", from: "experiments", to: "impact", route: "impact", label: "links immutable intervention ids", proposed: true },
  ],
  traces: [
    { id: "direct", name: "Direct map request", route: "build", steps: ["host", "skill", "cli", "scope", "compiler", "artifact", "session", "service", "viewer"] },
    { id: "experiment", name: "Staged experiment", route: "experiment", steps: ["host", "skill", "cli", "experiments", "compiler", "artifact", "session"] },
    { id: "local-question", name: "Sidebar question", route: "question", steps: ["viewer", "service", "router", "responder", "session", "service", "viewer"] },
    { id: "host-question", name: "Host-attached question", route: "host", steps: ["viewer", "service", "router", "hostbridge", "host"] },
    { id: "observer", name: "Proposed observation", route: "observe", steps: ["host", "hostevents", "observer", "experiments"] },
  ],
  impactStates: [
    { id: "activity", name: "Activity", current: "partly recorded", meaning: "Attend created or changed something.", examples: "checkpoint, plan, package, answer" },
    { id: "exposure", name: "Exposure", current: "incomplete", meaning: "A person or host actually received it.", examples: "render ack, host-answer delivery" },
    { id: "influence", name: "Influence", current: "not joined", meaning: "A downstream actor explicitly used or rejected it.", examples: "referenced plan change, explicit rejection" },
    { id: "impact", name: "Impact", current: "not measured", meaning: "A declared outcome differed against a defensible baseline.", examples: "less rework, faster decision, fewer corrections" },
  ],
  interrogations: [
    {
      id: "is-agent", target: "service", mode: "current",
      question: "Is Attend already a separate active agent?",
      answer: "No. The detached process is a reactive page and question service. Opportunity detection still lives in the active coding agent through the managed skill.",
    },
    {
      id: "own-context", target: "session", mode: "current",
      question: "Does Attend have its own session and context?",
      answer: "It has durable visualization/application state. It does not have one continuing provider thread: local and detached answer packets are rebuilt from the selected marks, recent turns, and implicated evidence for each question.",
    },
    {
      id: "measure-effect", target: "impact", mode: "impact",
      question: "Can we tell what Attend changed or influenced?",
      answer: "Not reliably today. Existing records cover activity. A new cross-boundary ledger needs explicit delivery, use, reversal, assignment, and outcome receipts before the system can distinguish exposure, influence, and causal impact.",
    },
    {
      id: "better-system", target: "observer", mode: "observer",
      question: "What would a better dedicated observer look like?",
      answer: "One project daemon can host isolated, session-scoped ObserverSessions fed by authenticated lifecycle events. Start in shadow mode, keep context bounded, enforce fairness and interruption budgets, and leave source expansion and host mutation outside its authority.",
    },
    {
      id: "why-defer", target: "skill", mode: "current",
      question: "When should Attend do nothing?",
      answer: "Whenever the user names a visual form or interaction that no executable member can satisfy exactly. Attend should create no substitute artifact; the coding agent resumes its normal just-in-time workflow and searches for a relevant repository precedent when one may exist.",
    },
  ],
};
