import { randomUUID } from "node:crypto";
import {
  lstat,
  mkdir,
  open,
  readFile,
  rename,
  stat,
  unlink,
} from "node:fs/promises";
import { dirname, isAbsolute, join, parse, relative, resolve, sep } from "node:path";

import {
  PROJECT_SCHEMA_VERSION,
  VIEW_ID,
  VIEW_VERSION,
} from "./constants.js";

export const MANAGED_MARKER = "attend-managed";

const PROJECT_DIRECTORY = ".attend";
const PROJECT_FILE = `${PROJECT_DIRECTORY}/project.json`;
const PROJECT_GITIGNORE = `${PROJECT_DIRECTORY}/.gitignore`;
const SKILL_TARGETS = Object.freeze([
  Object.freeze({
    id: "agents",
    path: ".agents/skills/attend-visualize/SKILL.md",
  }),
  Object.freeze({
    id: "claude",
    path: ".claude/skills/attend-visualize/SKILL.md",
  }),
]);
const OPENAI_METADATA_TARGET = Object.freeze({
  id: "agents",
  path: ".agents/skills/attend-visualize/agents/openai.yaml",
});

export const SKILL_TARGET_IDS = Object.freeze(
  SKILL_TARGETS.map((target) => target.id),
);

function selectedSkillTargets(agents) {
  if (agents === undefined || agents === null) return SKILL_TARGETS;
  if (!Array.isArray(agents)) {
    throw new TypeError("agents must be an array of skill target ids");
  }
  const unknown = agents.filter((id) => !SKILL_TARGET_IDS.includes(id));
  if (unknown.length) {
    const error = new Error(
      "Unknown agent target(s): " +
        unknown.join(", ") +
        ". Known targets: " +
        SKILL_TARGET_IDS.join(", ") +
        ".",
    );
    error.code = "UNKNOWN_AGENT_TARGET";
    throw error;
  }
  return SKILL_TARGETS.filter((target) => agents.includes(target.id));
}

function projectFileContents() {
  return `${JSON.stringify(
    {
      managedBy: MANAGED_MARKER,
      schemaVersion: PROJECT_SCHEMA_VERSION,
      sourceScope: {
        root: ".",
        recursiveExcludes: [".*", "node_modules"],
        explicitHiddenSourcesAllowed: true,
      },
      view: {
        id: VIEW_ID,
        version: VIEW_VERSION,
      },
    },
    null,
    2,
  )}\n`;
}

function gitignoreContents() {
  return `# ${MANAGED_MARKER}: local Attend runtime state\n/local/\n`;
}

export function managedSkillContents(source) {
  const normalized = source.replace(/^\uFEFF/, "").replace(/\r\n/g, "\n");
  if (normalized.includes(MANAGED_MARKER)) {
    return normalized.endsWith("\n") ? normalized : `${normalized}\n`;
  }
  const body = normalized.endsWith("\n") ? normalized : `${normalized}\n`;
  const frontmatter = body.match(/^---\n[\s\S]*?\n---\n/);
  if (frontmatter) {
    return `${frontmatter[0]}<!-- ${MANAGED_MARKER}: generated by Attend setup -->\n${body.slice(frontmatter[0].length)}`;
  }
  return `<!-- ${MANAGED_MARKER}: generated by Attend setup -->\n${body}`;
}

export function managedSkillMetadataContents(source) {
  const normalized = source.replace(/^\uFEFF/u, "").replace(/\r\n/gu, "\n");
  const body = normalized.endsWith("\n") ? normalized : `${normalized}\n`;
  if (body.includes(MANAGED_MARKER)) return body;
  return `# ${MANAGED_MARKER}: generated by Attend setup\n${body}`;
}

async function readExisting(path) {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") return null;
    throw error;
  }
}

async function assertDirectory(path) {
  let info;
  try {
    info = await stat(path);
  } catch (error) {
    if (error?.code === "ENOENT") {
      const missing = new Error(`Project root does not exist: ${path}`);
      missing.code = "PROJECT_ROOT_NOT_FOUND";
      throw missing;
    }
    throw error;
  }
  if (!info.isDirectory()) {
    const invalid = new Error(`Project root is not a directory: ${path}`);
    invalid.code = "INVALID_PROJECT_ROOT";
    throw invalid;
  }
}

function unsafePath(message, path) {
  const error = new Error(`${message}: ${path}`);
  error.code = "UNSAFE_SYMLINK";
  error.path = path;
  return error;
}

function isInside(root, candidate) {
  const child = relative(root, candidate);
  return child === "" || (child !== ".." && !child.startsWith(`..${sep}`));
}

function inferredManagedRoot(path) {
  const absolute = resolve(path);
  const filesystemRoot = parse(absolute).root;
  const parts = absolute.slice(filesystemRoot.length).split(sep).filter(Boolean);
  let marker = -1;
  for (let index = 0; index < parts.length; index += 1) {
    if (
      parts[index] === ".attend" ||
      parts[index] === ".agents" ||
      parts[index] === ".claude"
    ) {
      marker = index;
    }
  }
  if (marker < 0) return null;
  return resolve(filesystemRoot, ...parts.slice(0, marker));
}

async function pathInfo(path) {
  try {
    return await lstat(path);
  } catch (error) {
    if (error?.code === "ENOENT") return null;
    throw error;
  }
}

export async function assertSafeWritePath(root, path) {
  const boundary = resolve(root);
  const target = resolve(path);
  if (!isInside(boundary, target)) throw unsafePath("Write escapes project root", target);
  const parent = dirname(target);
  let cursor = boundary;
  for (const part of relative(boundary, parent).split(sep).filter(Boolean)) {
    cursor = join(cursor, part);
    const info = await pathInfo(cursor);
    if (!info) break;
    if (info.isSymbolicLink()) throw unsafePath("Refusing to traverse symbolic link", cursor);
    if (!info.isDirectory()) throw unsafePath("Write parent is not a directory", cursor);
  }
  const targetInfo = await pathInfo(target);
  if (targetInfo?.isSymbolicLink()) throw unsafePath("Refusing to replace symbolic link", target);
}

export async function ensureSafeDirectory(root, directory, mode = 0o700) {
  const boundary = resolve(root);
  const target = resolve(directory);
  if (!isInside(boundary, target)) throw unsafePath("Directory escapes project root", target);
  let cursor = boundary;
  for (const part of relative(boundary, target).split(sep).filter(Boolean)) {
    cursor = join(cursor, part);
    let info = await pathInfo(cursor);
    if (!info) {
      try {
        await mkdir(cursor, { mode });
      } catch (error) {
        if (error?.code !== "EEXIST") throw error;
      }
      info = await lstat(cursor);
    }
    if (info.isSymbolicLink()) throw unsafePath("Refusing to traverse symbolic link", cursor);
    if (!info.isDirectory()) throw unsafePath("Write parent is not a directory", cursor);
  }
}

async function writeAtomic(path, contents, { root } = {}) {
  const boundary = root === undefined ? inferredManagedRoot(path) : resolve(root);
  if (boundary) {
    await assertSafeWritePath(boundary, path);
    await ensureSafeDirectory(boundary, dirname(path));
  } else {
    await mkdir(dirname(path), { recursive: true });
  }
  const temporary = join(dirname(path), `.${randomUUID()}.tmp`);
  let handle;
  try {
    handle = await open(temporary, "wx", 0o600);
    await handle.writeFile(contents, "utf8");
    await handle.sync();
    await handle.close();
    handle = null;
    if (boundary) await assertSafeWritePath(boundary, path);
    await rename(temporary, path);
  } finally {
    await handle?.close().catch(() => {});
    await unlink(temporary).catch((error) => {
      if (error?.code !== "ENOENT") throw error;
    });
  }
}

export async function readJson(path) {
  const boundary = inferredManagedRoot(path);
  if (boundary) await assertSafeWritePath(boundary, path);
  const source = await readFile(path, "utf8");
  try {
    return JSON.parse(source);
  } catch (error) {
    const invalid = new Error(`Invalid JSON in ${path}`);
    invalid.code = "INVALID_JSON";
    invalid.path = path;
    invalid.cause = error;
    throw invalid;
  }
}

export async function writeJsonAtomic(path, value, options) {
  let encoded;
  try {
    encoded = JSON.stringify(value, null, 2);
  } catch (error) {
    throw new TypeError(`Value for ${path} is not JSON-serializable: ${error.message}`);
  }
  if (encoded === undefined) {
    throw new TypeError(`Value for ${path} is not JSON-serializable`);
  }
  await writeAtomic(path, `${encoded}\n`, options);
}

async function desiredFiles({ root, skillSource, skillMetadataSource, agents }) {
  const files = [
    {
      path: resolve(root, PROJECT_FILE),
      relativePath: PROJECT_FILE,
      contents: projectFileContents(),
    },
    {
      path: resolve(root, PROJECT_GITIGNORE),
      relativePath: PROJECT_GITIGNORE,
      contents: gitignoreContents(),
    },
  ];

  if (skillSource !== undefined && skillSource !== null) {
    if (typeof skillSource !== "string" || skillSource.length === 0) {
      throw new TypeError("skillSource must be a non-empty filesystem path");
    }
    const sourcePath = isAbsolute(skillSource)
      ? skillSource
      : resolve(root, skillSource);
    const source = await readFile(sourcePath, "utf8");
    const contents = managedSkillContents(source);
    for (const target of selectedSkillTargets(agents)) {
      files.push({
        path: resolve(root, target.path),
        relativePath: target.path,
        contents,
        sourcePath,
        agent: target.id,
      });
    }
  }

  if (skillMetadataSource !== undefined && skillMetadataSource !== null) {
    if (typeof skillMetadataSource !== "string" || skillMetadataSource.length === 0) {
      throw new TypeError("skillMetadataSource must be a non-empty filesystem path");
    }
    if (selectedSkillTargets(agents).some((target) => target.id === OPENAI_METADATA_TARGET.id)) {
      const sourcePath = isAbsolute(skillMetadataSource)
        ? skillMetadataSource
        : resolve(root, skillMetadataSource);
      const source = await readFile(sourcePath, "utf8");
      files.push({
        path: resolve(root, OPENAI_METADATA_TARGET.path),
        relativePath: OPENAI_METADATA_TARGET.path,
        contents: managedSkillMetadataContents(source),
        sourcePath,
        agent: OPENAI_METADATA_TARGET.id,
      });
    }
  }

  return files;
}

async function planFile(file, root) {
  await assertSafeWritePath(root, file.path);
  const existing = await readExisting(file.path);
  if (existing === null) {
    return {
      path: file.relativePath,
      action: "create",
      managed: true,
    };
  }
  if (existing === file.contents) {
    return {
      path: file.relativePath,
      action: "unchanged",
      managed: existing.includes(MANAGED_MARKER),
    };
  }
  if (!existing.includes(MANAGED_MARKER)) {
    return {
      path: file.relativePath,
      action: "conflict",
      managed: false,
      reason: "A differing file exists without the Attend managed marker.",
    };
  }
  return {
    path: file.relativePath,
    action: "update",
    managed: true,
  };
}

function setupResult(root, dryRun, planned) {
  return {
    root,
    dryRun,
    planned,
    created: [],
    updated: [],
    unchanged: planned
      .filter((effect) => effect.action === "unchanged")
      .map((effect) => effect.path),
    conflicts: planned
      .filter((effect) => effect.action === "conflict")
      .map((effect) => effect.path),
  };
}

/**
 * Plan or install Attend's project-scoped configuration.
 *
 * The complete plan is computed before the first write. Differing unmarked
 * files stop a real setup without leaving a partial installation behind.
 */
export async function setupProject({
  root,
  dryRun = false,
  skillSource,
  skillMetadataSource,
  agents,
} = {}) {
  if (typeof root !== "string" || root.length === 0) {
    throw new TypeError("setupProject requires a project root");
  }

  const projectRoot = resolve(root);
  await assertDirectory(projectRoot);
  const files = await desiredFiles({
    root: projectRoot,
    skillSource,
    skillMetadataSource,
    agents,
  });
  const planned = await Promise.all(files.map((file) => planFile(file, projectRoot)));
  const result = setupResult(projectRoot, Boolean(dryRun), planned);

  if (dryRun) return result;

  const conflict = planned.find((effect) => effect.action === "conflict");
  if (conflict) {
    const error = new Error(
      `Refusing to overwrite unmanaged file: ${conflict.path}`,
    );
    error.code = "UNMANAGED_FILE";
    error.path = conflict.path;
    error.plan = result;
    throw error;
  }

  for (const [index, file] of files.entries()) {
    const effect = planned[index];
    if (effect.action === "create" || effect.action === "update") {
      await writeAtomic(file.path, file.contents, { root: projectRoot });
      result[effect.action === "create" ? "created" : "updated"].push(
        effect.path,
      );
    }
  }

  return result;
}

export function projectPaths(root) {
  if (typeof root !== "string" || root.length === 0) {
    throw new TypeError("projectPaths requires a project root");
  }
  const projectRoot = resolve(root);
  return Object.freeze({
    root: projectRoot,
    directory: resolve(projectRoot, PROJECT_DIRECTORY),
    attendDir: resolve(projectRoot, PROJECT_DIRECTORY),
    project: resolve(projectRoot, PROJECT_FILE),
    projectFile: resolve(projectRoot, PROJECT_FILE),
    gitignore: resolve(projectRoot, PROJECT_GITIGNORE),
    gitignoreFile: resolve(projectRoot, PROJECT_GITIGNORE),
    local: resolve(projectRoot, PROJECT_DIRECTORY, "local"),
    localDir: resolve(projectRoot, PROJECT_DIRECTORY, "local"),
    sessions: resolve(projectRoot, PROJECT_DIRECTORY, "local", "sessions"),
    sessionsDir: resolve(projectRoot, PROJECT_DIRECTORY, "local", "sessions"),
    skill: resolve(projectRoot, SKILL_TARGETS[0].path),
    skillFile: resolve(projectRoot, SKILL_TARGETS[0].path),
    skills: Object.freeze(
      SKILL_TARGETS.map((target) =>
        Object.freeze({
          agent: target.id,
          relativePath: target.path,
          path: resolve(projectRoot, target.path),
        }),
      ),
    ),
    skillMetadata: Object.freeze({
      agent: OPENAI_METADATA_TARGET.id,
      relativePath: OPENAI_METADATA_TARGET.path,
      path: resolve(projectRoot, OPENAI_METADATA_TARGET.path),
    }),
  });
}
